WebBanSach/Controllers/LoaiSachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanSach.Models;

namespace WebBanSach.Controllers
{
    public class LoaiSachController : Controller
    {
        WebBanSachEntities db = new WebBanSachEntities();
        // GET: LoaiSach
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult LoaiSachPartial()
        {
            var loaisach = db.LoaiSaches.ToList();
            var chude = db.ChuDes.ToList();
            ViewBag.Chude = chude;
            return PartialView(loaisach);
        }

        public ActionResult LoaiSach_Sach(int? loaisachId)
        {
            var loaisach_sach = db.loaisach_sach(loaisachId).ToList();
            List<Sach_Tacgia_Thamgia_Result> sach_tacgia = new List<Sach_Tacgia_Thamgia_Result>();
            for (int i = 0; i < loaisach_sach.Count; i++)
            {
                var sach = db.Sach_Tacgia_Thamgia(loaisach_sach[i].MaSach).ToList();
                sach_tacgia.Add(sach[0]);
            }
            return View(sach_tacgia);
        }
        public JsonResult Test(int ? loaisachId)
        {
            var loaisach_sach = db.loaisach_sach(loaisachId).ToList();
            List<Sach_Tacgia_Thamgia_Result> sach_tacgia = new List<Sach_Tacgia_Thamgia_Result>();
            for (int i = 0; i < loaisach_sach.Count; i++)
            {
                var sach = db.Sach_Tacgia_Thamgia(loaisach_sach[i].MaSach).ToList();
                sach_tacgia.Add(sach[0]);
            }
            return Json(sach_tacgia,JsonRequestBehavior.AllowGet);
        }
        public ActionResult Ls_chude_sach(int?loaisachId,int? MaChuDe)
        {
            var chude_sach = db.chude_sach(MaChuDe).ToList();
            List<Sach_Tacgia_Thamgia_Result> sach_chude = new List<Sach_Tacgia_Thamgia_Result>();
            for (int i = 0; i < chude_sach.Count; i++)
            {
                var sach = db.Sach_Tacgia_Thamgia(chude_sach[i]).ToList();
                sach_chude.Add(sach[0]);
            }
            return View(sach_chude);
        }
    }
}

WebBanSach/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanSach.Models;

namespace WebBanSach.Controllers
{
    public class SachController : Controller
    {
        WebBanSachEntities db = new WebBanSachEntities();
        // GET: Sach
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult All_Sach()
        {
            var Sach = db.Saches.ToList();
            List<Sach_Tacgia_Thamgia_Result> sach_tacgia = new List<Sach_Tacgia_Thamgia_Result>();
            for (int i = 0; i < Sach.Count; i++)
            {
                var sachtg = db.Sach_Tacgia_Thamgia(Sach[i].MaSach).ToList();
                sach_tacgia.Add(sachtg[0]);
            }
            return View(sach_tacgia);
        }
    }
}

WebBanSach/Views/Shared/NguoiDungBanSach.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    @*Css của teamplate*@
    <link href="~/Content/CssLayoutNguoiDung/screen.css" rel="stylesheet" />
    <link href="~/Content/CssLayoutNguoiDung/fonts.css" rel="stylesheet" />
    @*Css tự thiết kế*@
    <link href="~/Content/CssLayoutNguoiDung/NguoiDungCss.css" rel="stylesheet" />
    @*font awesome*@
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    @*JS tự thiết kế*@
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/JSNguoiDung/NguoiDung-JS.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    @*chen css, jquery của nivo slider*@
    <link href="~/Nivo Slider/default.css" rel="stylesheet" />
    <link href="~/Nivo Slider/nivo-slider.css" rel="stylesheet" />
    <script src="~/Nivo Slider/jquery.nivo.slider.js"></script>
    <script src="~/Nivo Slider/jquery.nivo.slider.pack.js"></script>
</head>
<body>

    <div id="ToanTrang">
        <section class="blank">
            <div class="flash flash-top">
                <div class="Phone">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    (0962441498)
                </div>
                @*Tao div đang ký đang nhập*@
                <div class="DangKyDangNhap">
                    <a id="dangky" href="@Url.Action("DangKy", "Home")"><i class="fa fa-user-plus fa-fw" aria-hidden="true"></i>  Đăng Ký</a>
                    <a id="dangnhap" href="@Url.Action("DangNhap", "Home")"><i class="fa fa-sign-in fa-fw" aria-hidden="true"></i>  Đăng Nhập</a>
                </div>
            </div>
            <div class="flash success" id="divDanhMuc">
                <ul class="navMenu">
                    <li>
                        @Html.ActionLink("Trang Chủ", "Index", "Home")
                    </li>
                    <li>
                        <a href="#">Giới Thiệu</a>
                    </li>
                    <li>
                        <a href="#">Liên Hệ</a>
                    </li>
                    <li>
                        <a href="#">Hướng Dẫn</a>
                    </li>
                    <li>
                        <a href="#">Sách</a>
                    </li>
                </ul>
            </div>
        </section>
        <section>
            <div id="menutrai">
                @*hôp thoai tim kiem de dau cái menu3 này*@
                @*chèn vào nội dung của menutrai partial view*@
                @Html.Action("LoaiSachPartial", "LoaiSach")
            </div>
            @*nivo slider*@
            <div id="menuphai">
                <div class="slider-wrapper theme-default">
                    <div id="slider" class="nivoSlider">
                        <img src="~/Image/image_Nivo/sach-tet.jpg" />
                        <img src="~/Image/image_Nivo/sherlock-holmes.jpg" />
                        <img src="~/Image/image_Nivo/ve-dau-nhung-vet-thuong.jpg" />
                        <img src="~/Image/image_Nivo/hom-nay-toi-that-tinh.jpg" />
                    </div>
                </div>

                @*Div body*@
                <div id="noidung">
                    <div id="bartieude">Trang Chủ</div>
                    <div id="barsukien">
                        <div class="sort-button">
                          <div class="sort-bao" >
                              <span class="sort-sanpham">Sản phẩm chọn lọc</span>
                              <i class="fa fa-caret-down" id="caret" aria-hidden="true"></i>
                          </div>
                          <ul class="sort-list">
                              <li class="li-sort"><a href="#">Bán chạy nhất</a></li>
                              <li class="li-sort"><a href="#">Giảm giá nhiều nhất</a></li>
                              <li class="li-sort"><a href="#">Hàng mới nhập</a></li>
                              <li class="li-sort"><a href="#">Ngày xuất bản</a></li>
                              <li class="li-sort"><a href="#">Giá: Thấp đến Cao</a></li>
                              <li class="li-sort"><a href="#">Giá: Cao đến Thấp</a></li>
                              <li class="li-sort"><a href="#">Sản phẩm chọn lọc</a></li>
                          </ul>
                        </div>
                    </div>
                    @RenderBody() @*phải có thuộc tính này... định nghĩa đây là layout để các trang khác kế thừa*@
                    <div id="content1"></div>
                        @*@Html.Action("All_Sach","Sach");*@
                    </div>
            </div>
            <div style="clear:both"></div>

            <section class="blank items">
                <div>
                    <p id="asd" data-id="1" class="button button-buy">Buy button (full width for columns)</p>
                    
                    </div>
            </section>
    </div>

    @*nivo slider js*@
    <script type="text/javascript">
        $(window).load(function () {
            $('#slider').nivoSlider();
        });
    </script>
    
</body>
</html>

WebBanSach/Views/Shared/ViewTest.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

WebBanSach/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    @*Css của teamplate*@
    <link href="~/Content/CssLayoutNguoiDung/screen.css" rel="stylesheet" />
    <link href="~/Content/CssLayoutNguoiDung/fonts.css" rel="stylesheet" />
    @*Css tự thiết kế*@
    <link href="~/Content/CssLayoutNguoiDung/NguoiDungCss.css" rel="stylesheet" />
    @*font awesome*@
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    @*JS tự thiết kế*@
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/JSNguoiDung/NguoiDung-JS.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    @*chen css, jquery của nivo slider*@
    <link href="~/Nivo Slider/default.css" rel="stylesheet" />
    <link href="~/Nivo Slider/nivo-slider.css" rel="stylesheet" />
    <script src="~/Nivo Slider/jquery.nivo.slider.js"></script>
    <script src="~/Nivo Slider/jquery.nivo.slider.pack.js"></script>
</head>
<body>

    <div id="ToanTrang">
        <section class="blank">
            <div class="flash">
                <div class="Phone">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    (0962441498)
                </div>
                @*Tao div đang ký đang nhập*@
                <div class="DangKyDangNhap">
                    <a id="dangky" href="@Url.Action("DangKy", "Home")"><i class="fa fa-user-plus fa-fw" aria-hidden="true"></i>  Đăng Ký</a>
                    <a id="dangnhap" href="@Url.Action("DangNhap", "Home")"><i class="fa fa-sign-in fa-fw" aria-hidden="true"></i>  Đăng Nhập</a>
                </div>
            </div>
            <div class="flash success" id="divDanhMuc">
                <ul class="navMenu">
                    <li>
                        @Html.ActionLink("Trang Chủ", "Index", "Home")
                    </li>
                    <li>
                        <a href="#">Giới Thiệu</a>
                    </li>
                    <li>
                        <a href="#">Liên Hệ</a>
                    </li>
                    <li>
                        <a href="#">Hướng Dẫn</a>
                    </li>
                    <li>
                        <a href="#">Sách</a>
                    </li>
                </ul>
            </div>
        </section>
        <section>
            <div id="menutrai">
                @*hôp thoai tim kiem de dau cái menu3 này*@
                @*chèn vào nội dung của menutrai partial view*@
                @Html.Action("LoaiSachPartial", "LoaiSach")
            </div>
            @*nivo slider*@
            <div id="menuphai">
                

                @*Div body*@
                <div id="noidung">
                    <div id="bartieude">Trang Chủ</div>
                    <div id="barsukien">
                        <div class="sort-button">
                            <div class="sort-bao">
                                <span class="sort-sanpham">Sản phẩm chọn lọc</span>
                                <i class="fa fa-caret-down" id="caret" aria-hidden="true"></i>
                            </div>
                            <ul class="sort-list">
                                <li class="li-sort"><a href="#">Bán chạy nhất</a></li>
                                <li class="li-sort"><a href="#">Giảm giá nhiều nhất</a></li>
                                <li class="li-sort"><a href="#">Hàng mới nhập</a></li>
                                <li class="li-sort"><a href="#">Ngày xuất bản</a></li>
                                <li class="li-sort"><a href="#">Giá: Thấp đến Cao</a></li>
                                <li class="li-sort"><a href="#">Giá: Cao đến Thấp</a></li>
                                <li class="li-sort"><a href="#">Sản phẩm chọn lọc</a></li>
                            </ul>
                        </div>
                    </div>
                    @RenderBody() @*phải có thuộc tính này... định nghĩa đây là layout để các trang khác kế thừa*@
                    <div id="content1"></div>
                    @*@Html.Action("All_Sach","Sach");*@
                </div>
            </div>
            <div style="clear:both"></div>

            <section class="blank items">
                <div>
                    <p id="asd" data-id="1" class="button button-buy">Buy button (full width for columns)</p>

                </div>
            </section>
    </div>


</body>
</html>